# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#

language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio run -e d1_mini
  - platformio run -e nodemcu
  - platformio run -e nodemcuv2

before_deploy:
  - curl -LJ https://github.com/ToolboxBodensee/led_tunnel/releases/download/travis-latest/version --output version.old
  - version=$(grep -Eo '[0-9]{1,16}' version.old) || true
  - echo $((++version))>version
  - git tag -f travis-latest
  - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh travis-latest
  - git remote remove gh

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
